import { StyleSheet } from 'react-native';
import { COLORS, FONT_WEIGHT } from '../../../theme';

export default StyleSheet.create({
  actualInput: { backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: COLORS.border, borderRadius: 8, color: '#fff', padding: 10, fontSize: 16, marginTop: 4, marginBottom: 12 },
  inputGroup: { marginTop: 8 },
  sectionTitle: { fontSize: 13, fontWeight: FONT_WEIGHT.bold, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: 1.5, marginBottom: 12, marginLeft: 4, marginTop: 16 },
  card: { padding: 16, marginBottom: 12, backgroundColor: 'rgba(30, 41, 59, 0.7)', borderWidth: 1, borderColor: 'rgba(245, 158, 11, 0.3)' },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  roomBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(16, 185, 129, 0.15)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, gap: 6 },
  roomText: { fontSize: 12, fontWeight: FONT_WEIGHT.bold, color: '#34d399' },
  dateText: { fontSize: 12, color: '#64748b', fontWeight: '500' },
  cardBody: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 12 },
  tenantName: { fontSize: 16, fontWeight: FONT_WEIGHT.bold, color: '#f8fafc', marginBottom: 4 },
  referenceText: { fontSize: 13, color: '#94a3b8' },
  amount: { fontSize: 20, fontWeight: FONT_WEIGHT.heavy, color: '#f59e0b' },
  cardFooter: { borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.05)', paddingTop: 12, alignItems: 'center' },
  reviewText: { fontSize: 13, color: '#fbbf24', fontWeight: FONT_WEIGHT.bold, letterSpacing: 0.5 },

  modalOverlay: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.8)', justifyContent: 'center', alignItems: 'center', padding: 16 },
  modalContainer: { width: '100%', backgroundColor: '#1e293b', borderRadius: 16, overflow: 'hidden', maxHeight: '90%', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.05)' },
  modalTitle: { fontSize: 18, fontWeight: '700', color: '#f8fafc' },
  modalBody: { padding: 16 },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  infoLabel: { fontSize: 14, color: '#94a3b8' },
  infoValue: { fontSize: 14, color: '#f8fafc', fontWeight: '500' },
  infoValueBold: { fontSize: 18, color: '#10b981', fontWeight: '800' },
  proofLabel: { fontSize: 14, fontWeight: '600', color: '#cbd5e1', marginTop: 16, marginBottom: 8 },
  proofImage: { width: '100%', height: 300, backgroundColor: '#0f172a', borderRadius: 8, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  noProofBox: { width: '100%', height: 100, backgroundColor: 'rgba(15, 23, 42, 0.5)', borderRadius: 8, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', borderStyle: 'dashed' },
  noProofText: { color: '#64748b' },
  actionRow: { flexDirection: 'row', gap: 12, marginTop: 24 },
  actionBtn: { flex: 1, padding: 14, borderRadius: 10, alignItems: 'center' },
  rejectBtn: { backgroundColor: 'rgba(239, 68, 68, 0.1)', borderWidth: 1, borderColor: 'rgba(239, 68, 68, 0.3)' },
  rejectBtnText: { color: '#ef4444', fontWeight: '700', fontSize: 16 },
  approveBtn: { backgroundColor: '#10b981' },
  actionBtnText: { color: '#fff', fontWeight: '700', fontSize: 16 },

  confirmModalContainer: { width: '85%', backgroundColor: '#1e293b', borderRadius: 20, overflow: 'hidden', padding: 24, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', alignItems: 'center' },
  confirmHeader: { alignItems: 'center', marginBottom: 16 },
  confirmTitle: { fontSize: 20, fontWeight: '800', color: '#f8fafc', marginTop: 12, textAlign: 'center' },
  confirmMessage: { fontSize: 15, color: '#94a3b8', textAlign: 'center', lineHeight: 22, marginBottom: 30, paddingHorizontal: 10 },
  confirmActionRow: { flexDirection: 'row', gap: 12, width: '100%' },
  confirmCancelBtn: { flex: 1, padding: 14, borderRadius: 12, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.05)' },
  confirmCancelText: { color: '#cbd5e1', fontWeight: '600', fontSize: 16 },
  confirmExecuteBtn: { flex: 1, padding: 14, borderRadius: 12, alignItems: 'center' },
  rejectSolidBtn: { backgroundColor: '#ef4444' }
});
