import { StyleSheet, Platform } from 'react-native';
import { COLORS, RADIUS, SPACING, FONT_WEIGHT, SHADOWS } from '../theme';

export default StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: '#070D18',
  },

  // Fixed Top Navigation Header
  header: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? 6 : 8,
    paddingBottom: 12,
    backgroundColor: '#070D18',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.06)',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitleGroup: {
    flex: 1,
  },
  screenTitle: { 
    fontSize: 18.5, 
    fontWeight: '800', 
    color: '#FFFFFF',
    letterSpacing: -0.3,
  },
  screenSubtitle: { 
    fontSize: 11, 
    color: '#64748B', 
    fontWeight: '500',
    marginTop: 1,
  },
  createBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#10B981',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 18,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
  },
  createBtnText: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#042F2E',
  },

  // Main Scrollable Area
  scroll: { 
    paddingBottom: 32,
  },

  // KPI Overview Strip
  statsRow: { 
    flexDirection: 'row', 
    backgroundColor: '#0C1322', 
    borderRadius: 14, 
    borderWidth: 1, 
    borderColor: 'rgba(255, 255, 255, 0.06)',
    paddingVertical: 10,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 12,
  },
  statBox: { 
    flex: 1, 
    alignItems: 'center', 
    justifyContent: 'center',
  },
  statDivider: { 
    borderRightWidth: 1, 
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  statLabel: { 
    fontSize: 9.5, 
    fontWeight: '800', 
    color: '#64748B', 
    letterSpacing: 0.7, 
    marginBottom: 2,
    textTransform: 'uppercase',
  },
  statValue: { 
    fontSize: 16, 
    fontWeight: '800', 
    color: '#FFFFFF',
  },

  // Search & Filters
  searchSection: { 
    paddingHorizontal: 16, 
    marginBottom: 10,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0C1322',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 12,
    height: 42,
    marginBottom: 8,
  },
  searchInput: { 
    flex: 1, 
    marginLeft: 8, 
    color: '#FFFFFF', 
    fontSize: 13, 
    paddingVertical: 0,
  },
  catScroll: { 
    gap: 6, 
    paddingVertical: 2,
  },
  catBtn: { 
    paddingHorizontal: 12, 
    paddingVertical: 6, 
    borderRadius: 8, 
    backgroundColor: '#0C1322',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.07)',
  },
  catBtnActive: { 
    backgroundColor: 'rgba(16, 185, 129, 0.15)', 
    borderColor: '#10B981',
  },
  catText: { 
    fontSize: 11.5, 
    color: '#94A3B8', 
    fontWeight: '600',
  },
  catTextActive: { 
    color: '#10B981', 
    fontWeight: '800',
  },

  // Tip Card (Matches tips-cms.png)
  tipCard: { 
    backgroundColor: '#0C1322', 
    borderRadius: 16, 
    borderWidth: 1, 
    borderColor: 'rgba(255, 255, 255, 0.07)', 
    padding: 13, 
    marginBottom: 10, 
    marginHorizontal: 16,
  },
  inactiveCard: { 
    opacity: 0.65,
    borderColor: 'rgba(255, 255, 255, 0.04)',
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  categoryAndSavings: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
  },
  categoryBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  categoryBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  savingsText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#10B981',
  },
  statusWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '700',
  },
  statusPublished: {
    color: '#10B981',
  },
  statusDraft: {
    color: '#64748B',
  },
  tipTitle: { 
    fontSize: 14.5, 
    fontWeight: '700', 
    color: '#FFFFFF', 
    letterSpacing: -0.2, 
    marginTop: 8, 
    marginBottom: 3,
  },
  tipMessage: { 
    fontSize: 12, 
    color: '#94A3B8', 
    lineHeight: 17.5,
  },
  cardBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
  },
  metaLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  tipIdText: {
    fontSize: 10.5,
    color: '#64748B',
    fontWeight: '700',
    letterSpacing: 0.5,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  engagementWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  engItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3.5,
  },
  engText: {
    fontSize: 10.5,
    color: '#64748B',
    fontWeight: '600',
  },
  actionsWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconActionBtn: {
    width: 28,
    height: 28,
    borderRadius: 7,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteActionBtn: {
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    borderColor: 'rgba(239, 68, 68, 0.2)',
  },

  // Loading & Empty States
  loaderContainer: { 
    alignItems: 'center', 
    justifyContent: 'center',
    paddingVertical: 60,
  },
  loaderText: { 
    marginTop: 10, 
    color: '#94A3B8', 
    fontSize: 13,
    fontWeight: '500',
  },
  emptyState: { 
    alignItems: 'center', 
    justifyContent: 'center',
    paddingVertical: 50, 
    paddingHorizontal: 24,
  },
  emptyIconWrap: {
    width: 60,
    height: 60,
    borderRadius: 18,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  emptyTitle: { 
    fontSize: 16, 
    fontWeight: '700', 
    color: '#FFFFFF', 
    marginBottom: 4,
  },
  emptyDesc: { 
    fontSize: 12.5, 
    color: '#64748B', 
    textAlign: 'center', 
    lineHeight: 18,
    marginBottom: 16,
  },
  emptyActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#10B981',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
  },
  emptyActionBtnText: {
    color: '#042F2E',
    fontSize: 12.5,
    fontWeight: '800',
  },

  // Modal Form Styles (Integrated Centered Modal)
  modalForm: { 
    gap: 12,
  },
  modalInputGroup: { 
    gap: 5,
  },
  modalLabel: { 
    fontSize: 11, 
    fontWeight: '800', 
    color: '#94A3B8', 
    letterSpacing: 0.5,
  },
  modalInput: { 
    backgroundColor: '#070D18', 
    borderRadius: 10, 
    paddingHorizontal: 12,
    paddingVertical: 9,
    color: '#FFFFFF',
    fontSize: 13,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  modalTextArea: { 
    minHeight: 80, 
    textAlignVertical: 'top',
    lineHeight: 18,
  },
  modalCategoryWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  modalCategoryChip: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 7,
    backgroundColor: '#070D18',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  modalCategoryChipActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.15)',
    borderColor: '#10B981',
  },
  modalCategoryChipText: {
    fontSize: 11,
    color: '#94A3B8',
    fontWeight: '600',
  },
  modalCategoryChipTextActive: {
    color: '#10B981',
    fontWeight: '800',
  },
  iconPreviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconPreviewBox: {
    width: 38,
    height: 38,
    borderRadius: 9,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  presetIconsScroll: {
    gap: 6,
    paddingVertical: 4,
  },
  presetIconBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#070D18',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  presetIconBtnActive: {
    backgroundColor: 'rgba(16, 185, 129, 0.2)',
    borderColor: '#10B981',
  },
  statusSettingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  statusSettingTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  statusSettingDesc: {
    fontSize: 10.5,
    color: '#64748B',
    marginTop: 1,
  },

  // Modal Action Buttons (Never Overflows)
  modalActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
    width: '100%',
  },
  modalBtnSecondary: {
    flex: 1,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  modalBtnSecondaryText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#94A3B8',
  },
  modalBtnPrimary: {
    flex: 1.2,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10B981',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 2,
  },
  modalBtnPrimaryText: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#042F2E',
  },
});
