import { StyleSheet } from 'react-native';
import { COLORS, SPACING, RADIUS, FONT_WEIGHT } from '../theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  scroll: { padding: SPACING.lg },
  title: { fontSize: 28, fontWeight: FONT_WEIGHT.bold, color: COLORS.textPrimary },
  subtitle: { fontSize: 14, color: COLORS.textMuted, marginBottom: SPACING.xl },
  profileCard: { padding: 20, marginBottom: SPACING.xl, borderRadius: RADIUS.xxl },
  profileTop: { flexDirection: 'row', alignItems: 'center', gap: 16, marginBottom: 16 },
  avatar: { width: 60, height: 60, borderRadius: 30, backgroundColor: 'rgba(34,197,94,0.1)', alignItems: 'center', justifyContent: 'center' },
  profileInfo: { flex: 1 },
  profileName: { fontSize: 18, fontWeight: FONT_WEIGHT.bold, color: COLORS.textPrimary },
  profileEmail: { fontSize: 13, color: COLORS.textSecondary, marginBottom: 4 },
  roleBadge: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4, backgroundColor: 'rgba(255,255,255,0.05)' },
  roleText: { fontSize: 9, fontWeight: '800', color: COLORS.primary, letterSpacing: 1 },
  editProfileBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingTop: 12, borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.05)' },
  editProfileText: { fontSize: 12, color: COLORS.primary, fontWeight: '600' },

  groupTitle: { fontSize: 11, fontWeight: '800', color: COLORS.textMuted, letterSpacing: 1.5, marginBottom: 8, marginLeft: 4 },
  menuCard: { padding: 8, marginBottom: SPACING.xl, borderRadius: RADIUS.xl },
  menuItem: { flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: RADIUS.lg },
  highlightedItem: { backgroundColor: 'rgba(34,197,94,0.05)' },
  menuIcon: { width: 40, height: 40, borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.05)', alignItems: 'center', justifyContent: 'center', marginRight: 14 },
  menuContent: { flex: 1 },
  menuLabel: { fontSize: 15, fontWeight: '600', color: COLORS.textPrimary },
  menuValue: { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },
  logoutBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, marginTop: 10, paddingVertical: 16 },
  logoutText: { fontSize: 15, fontWeight: '700', color: COLORS.danger },
  footerVersion: { textAlign: 'center', fontSize: 11, color: COLORS.textMuted, marginTop: 20 },
  confirmMsg: { fontSize: 15, color: COLORS.textSecondary, textAlign: 'center', lineHeight: 22 },
  form: { gap: 16, width: '100%' },
  inputGroup: { gap: 8 },
  label: { fontSize: 12, fontWeight: FONT_WEIGHT.heavy, color: COLORS.textMuted, letterSpacing: 1 },
  input: { backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 12, padding: 14, color: COLORS.textPrimary, borderWidth: 1, borderColor: COLORS.border },
  toggleList: { width: '100%', gap: 12 },
  toggleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 8 },
  toggleContent: { flex: 1 },
  toggleLabel: { fontSize: 15, color: COLORS.textPrimary, fontWeight: '600' },
  toggleDesc: { fontSize: 12, color: COLORS.textMuted, marginTop: 2 }
});
