import { StyleSheet, Platform, StatusBar } from 'react-native';
import { COLORS } from '../theme';

export default StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: COLORS.background 
  },
  scroll: { 
    flexGrow: 1,
    paddingHorizontal: 16, 
    paddingTop: Platform.OS === 'ios' ? 56 : (StatusBar.currentHeight || 20) + 16,
    paddingBottom: 110, // Clear floating navigation bar
  },
  fullWidth: {
    width: '100%',
  },

  // Compact Header (No large hero)
  compactHeader: {
    marginBottom: 16,
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.4,
  },
  pageSubtitle: {
    fontSize: 13,
    color: '#94A3B8',
    marginTop: 4,
    lineHeight: 18,
  },

  // Period Tabs (Daily | Weekly | Monthly)
  tabRow: { 
    flexDirection: 'row', 
    gap: 6, 
    marginBottom: 12,
    backgroundColor: '#0C1322',
    borderRadius: 14,
    padding: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
  },
  tabBtn: { 
    flex: 1, 
    paddingVertical: 7, 
    borderRadius: 10, 
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabActive: { 
    backgroundColor: 'rgba(16, 185, 129, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
  },
  tabText: { 
    fontSize: 12, 
    color: '#64748B', 
    fontWeight: '600',
  },
  tabTextActive: { 
    color: '#10B981', 
    fontWeight: '700',
  },

  // Progress Card (Matches smart-budgeting.png)
  progressCard: { 
    backgroundColor: '#0C1322',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 16,
    marginBottom: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  liveIndicatorWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 6,
  },
  liveDotWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.25)',
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#10B981',
  },
  liveText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#10B981',
    letterSpacing: 0.5,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 3.5,
    borderRadius: 8,
    borderWidth: 1,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  progressCenter: { 
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cyclePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.25)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    marginTop: 8,
  },
  cyclePillText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#F59E0B',
  },
  mainActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 14,
    width: '100%',
  },
  mainEditBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.25)',
  },
  mainEditBtnText: {
    color: '#10B981',
    fontSize: 12.5,
    fontWeight: '700',
  },
  mainResetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.2)',
  },
  mainResetBtnText: {
    color: '#EF4444',
    fontSize: 12.5,
    fontWeight: '600',
  },

  // Daily Spend Target Recommendation (Matches smart-budgeting.png)
  targetCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#0C1322',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.2)',
    padding: 13,
    marginBottom: 12,
  },
  targetIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  targetContent: {
    flex: 1,
  },
  targetLabel: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#10B981',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  targetDesc: {
    fontSize: 12.5,
    color: '#CBD5E1',
    marginTop: 2,
    fontWeight: '500',
  },

  // Section Headers
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginTop: 4,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#94A3B8',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },

  // Budget Breakdown (Priority Section)
  breakdownCard: { 
    backgroundColor: '#0C1322',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 15,
    marginBottom: 12,
  },
  // Visual Math Banner: [BUDGET] - [USED] = [REMAINING]
  mathContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    padding: 12,
    marginBottom: 12,
  },
  mathCol: {
    flex: 1,
    alignItems: 'center',
  },
  mathLabel: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#64748B',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    marginBottom: 3,
    textAlign: 'center',
  },
  mathValue: {
    fontSize: 14.5,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  mathSub: {
    fontSize: 10.5,
    color: '#06B6D4',
    marginTop: 2,
    fontWeight: '600',
    textAlign: 'center',
  },
  mathSign: {
    width: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mathSignText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#64748B',
  },
  // Status Explanation Banner
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 14,
  },
  statusText: {
    fontSize: 11.5,
    fontWeight: '600',
    flex: 1,
  },
  // Multi-period Breakdown Bars (Daily, Weekly, Monthly)
  breakdownGrid: { 
    gap: 12,
  },
  breakdownItem: { 
    gap: 4,
  },
  breakdownItemHeader: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between',
  },
  breakdownItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  breakdownIconBadge: {
    width: 26,
    height: 26,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  breakdownLabel: { 
    fontSize: 12, 
    color: '#FFFFFF', 
    fontWeight: '700',
  },
  breakdownAmounts: { 
    flexDirection: 'row', 
    alignItems: 'center',
    gap: 4,
  },
  breakdownSpent: { 
    fontSize: 12, 
    color: '#FFFFFF', 
    fontWeight: '700',
  },
  breakdownLimit: { 
    fontSize: 11.5, 
    color: '#64748B',
  },
  breakdownPct: { 
    fontSize: 11, 
    fontWeight: '700', 
    marginLeft: 6,
  },
  barTrack: { 
    height: 6, 
    backgroundColor: 'rgba(255, 255, 255, 0.07)', 
    borderRadius: 3, 
    overflow: 'hidden',
  },
  barFill: { 
    height: '100%', 
    borderRadius: 3,
  },

  // Budget Comparison Card
  compCard: { 
    backgroundColor: '#0C1322',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 15,
    marginBottom: 12,
  },
  compHeader: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  compPeriodRow: { 
    flexDirection: 'row', 
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 12,
    padding: 3,
    marginBottom: 12,
    width: '100%',
  },
  compPeriodBtn: { 
    flex: 1,
    paddingVertical: 7, 
    borderRadius: 9, 
    alignItems: 'center',
    justifyContent: 'center',
  },
  compPeriodActive: { 
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.4)',
  },
  compPeriodText: { 
    fontSize: 11.5, 
    color: '#64748B', 
    fontWeight: '600',
  },
  compPeriodTextActive: { 
    color: '#38BDF8', 
    fontWeight: '700',
  },
  compBody: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    padding: 14,
    marginBottom: 12,
  },
  compCol: { 
    flex: 1, 
    alignItems: 'center',
  },
  compColLabel: { 
    fontSize: 11, 
    color: '#64748B', 
    fontWeight: '600',
    marginBottom: 4,
  },
  compColVal: { 
    fontSize: 17, 
    fontWeight: '800', 
    color: '#FFFFFF',
  },
  compColSub: { 
    fontSize: 11, 
    color: '#06B6D4', 
    marginTop: 2,
    fontWeight: '600',
  },
  compArrow: { 
    width: 32, 
    alignItems: 'center', 
    justifyContent: 'center',
  },
  compBadge: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    gap: 6, 
    paddingHorizontal: 12, 
    paddingVertical: 8, 
    borderRadius: 10,
    borderWidth: 1,
  },
  compBadgeText: { 
    fontSize: 11.5, 
    fontWeight: '600', 
    flex: 1,
  },

  // Smart Insight (Compact Card)
  insightCard: {
    backgroundColor: '#0C1322',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.22)',
    padding: 14,
    marginBottom: 12,
  },
  insightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  insightBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#10B981',
    letterSpacing: 0.5,
  },
  insightTitle: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  insightDesc: {
    fontSize: 12,
    color: '#94A3B8',
    lineHeight: 18,
  },

  // Empty State
  emptyBudgetCard: { 
    backgroundColor: '#0C1322',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 24,
    alignItems: 'center',
    marginBottom: 14,
  },
  emptyBudgetIconWrap: { 
    width: 64, 
    height: 64, 
    borderRadius: 20, 
    backgroundColor: 'rgba(16, 185, 129, 0.12)', 
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.25)',
    alignItems: 'center', 
    justifyContent: 'center', 
    marginBottom: 12,
  },
  emptyBudgetTitle: { 
    fontSize: 17, 
    fontWeight: '800', 
    color: '#FFFFFF', 
    marginBottom: 4,
  },
  emptyBudgetDesc: { 
    fontSize: 12.5, 
    color: '#94A3B8', 
    textAlign: 'center', 
    lineHeight: 18, 
    paddingHorizontal: 12, 
    marginBottom: 18,
  },
  emptyBudgetBtn: { 
    backgroundColor: '#10B981',
    paddingVertical: 12, 
    paddingHorizontal: 24, 
    borderRadius: 12, 
    alignItems: 'center', 
    width: '100%',
  },
  emptyBudgetBtnText: { 
    color: '#042F2E', 
    fontSize: 13.5, 
    fontWeight: '800',
  },

  // Loading State
  loadingCard: { 
    backgroundColor: '#0C1322',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 240,
    marginBottom: 14,
  },
  loadingText: { 
    fontSize: 13, 
    color: '#94A3B8', 
    marginTop: 12,
  },

  // Modal Styles (Manual Edit Budget - No Min/Max limits)
  budgetInputContainer: { 
    paddingVertical: 10,
    alignItems: 'center',
    width: '100%',
  },
  currentBudgetPill: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
    marginBottom: 14,
  },
  currentBudgetText: {
    fontSize: 12,
    color: '#94A3B8',
    fontWeight: '600',
  },
  budgetInputWrap: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'center', 
    backgroundColor: '#070D18',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(16, 185, 129, 0.3)',
    paddingHorizontal: 16, 
    height: 62, 
    width: '100%',
    marginBottom: 8,
  },
  currencyLabel: { 
    fontSize: 26, 
    fontWeight: '800', 
    color: '#10B981', 
    marginRight: 6,
  },
  inputModal: { 
    fontSize: 28, 
    fontWeight: '800', 
    color: '#FFFFFF', 
    height: '100%', 
    textAlign: 'center',
    flex: 1,
    paddingVertical: 0,
  },
  livePreviewContainer: {
    alignItems: 'center',
    marginBottom: 14,
    paddingVertical: 4,
  },
  livePreviewText: {
    color: '#10B981',
    fontSize: 12.5,
    fontWeight: '600',
  },
  presetChipsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  presetChip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  presetChipText: {
    color: '#CBD5E1',
    fontSize: 12,
    fontWeight: '700',
  },
});
