import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import { COLORS } from '../../../styles/theme';

export default function DynamicQRCode({ invoiceNumber, amount, method = 'GCash' }) {
  // Construct a standard QR payload (simulating EMVCo QR code format used by GCash/Maya)
  // In a real production system, this would be generated by a Payment Gateway API (like PayMongo)
  const qrPayload = JSON.stringify({
    merchant: 'Wattipid Submetering',
    invoice: invoiceNumber,
    amount: parseFloat(amount || 0).toFixed(2),
    currency: 'PHP',
    method: method,
    timestamp: new Date().toISOString()
  });

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Scan to Pay via {method}</Text>
      
      <View style={styles.qrWrapper}>
        <QRCode
          value={qrPayload}
          size={200}
          color={COLORS.text}
          backgroundColor="white"
        />
      </View>

      <Text style={styles.instructions}>
        Amount Due: <Text style={styles.amount}>₱{parseFloat(amount || 0).toFixed(2)}</Text>
      </Text>
      <Text style={styles.subText}>
        Invoice #{invoiceNumber}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#fff',
    borderRadius: 16,
    marginVertical: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 }
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000', // COLORS.text doesn't exist in new theme
    marginBottom: 20,
    textAlign: 'center'
  },
  qrWrapper: {
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  instructions: {
    fontSize: 16,
    color: '#666',
    marginTop: 20,
  },
  amount: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  subText: {
    fontSize: 12,
    color: '#666',
    marginTop: 8,
  }
});
