import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import { COLORS } from '../../../styles/theme';

export default function DynamicQRCode({ invoiceNumber, amount, method = 'GCash' }) {
  // Construct a standard QR payload (simulating EMVCo QR code format used by GCash/Maya)
  // In a real production system, this would be generated by a Payment Gateway API (like PayMongo)
  const qrPayload = JSON.stringify({
    merchant: 'Wattipid Submetering',
    invoice: invoiceNumber,
    amount: parseFloat(amount || 0).toFixed(2),
    currency: 'PHP',
    method: method,
    timestamp: new Date().toISOString()
  });

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Scan to Pay via {method}</Text>
      
      <View style={styles.qrWrapper}>
        <QRCode
          value={qrPayload}
          size={160}
          color="#000"
          backgroundColor="white"
        />
      </View>

      <Text style={styles.instructions}>
        Amount Due: <Text style={styles.amount}>₱{parseFloat(amount || 0).toFixed(2)}</Text>
      </Text>
      <Text style={styles.subText}>
        Invoice #{invoiceNumber}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 14,
    marginVertical: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    maxWidth: 220,
    alignSelf: 'center',
    width: '100%',
  },
  title: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#000',
    marginBottom: 10,
    textAlign: 'center',
  },
  qrWrapper: {
    padding: 10,
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  instructions: {
    fontSize: 12.5,
    color: '#64748B',
    marginTop: 10,
    fontWeight: '500',
  },
  amount: {
    fontSize: 14,
    fontWeight: '800',
    color: '#10B981',
  },
  subText: {
    fontSize: 11,
    color: '#94A3B8',
    marginTop: 4,
    fontWeight: '600',
  }
});
