import { StyleSheet, Platform } from 'react-native';
import { COLORS, FONT_SIZE, FONT_WEIGHT, SPACING, RADIUS } from '../../theme';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    header: {
        paddingHorizontal: SPACING.lg,
        paddingTop: Platform.OS === 'android' ? 40 : SPACING.lg,
        paddingBottom: SPACING.md,
        backgroundColor: COLORS.surface,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.05)',
        alignItems: 'center'
    },
    headerTitleContainer: {
        alignItems: 'center',
    },
    appTitle: {
        fontSize: 14,
        fontWeight: FONT_WEIGHT.heavy,
        color: COLORS.primary,
        letterSpacing: 2,
        marginBottom: 6,
        textAlign: 'center',
        textTransform: 'uppercase'
    },
    modalTitle: {
        fontSize: FONT_SIZE.xl,
        fontWeight: FONT_WEIGHT.heavy,
        color: COLORS.textPrimary,
        textAlign: 'center',
        letterSpacing: 0.5
    },
    versionBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        paddingVertical: 8,
    },
    versionText: {
        fontSize: 11,
        color: COLORS.info,
        fontWeight: FONT_WEIGHT.bold,
    },
    subtitle: {
        fontSize: 14,
        color: COLORS.textSecondary,
        textAlign: 'center',
        paddingHorizontal: SPACING.xl,
        paddingVertical: SPACING.lg,
        lineHeight: 22
    },
    centerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: SPACING.xl,
    },
    loadingText: {
        marginTop: SPACING.md,
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.md,
    },
    errorText: {
        marginTop: SPACING.md,
        color: COLORS.danger,
        textAlign: 'center',
        marginBottom: SPACING.lg,
    },
    retryBtn: {
        backgroundColor: 'rgba(255,255,255,0.05)',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: RADIUS.md,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    retryBtnText: {
        color: COLORS.textPrimary,
        fontWeight: FONT_WEIGHT.bold,
    },
    scrollView: {
        flex: 1,
        backgroundColor: 'rgba(255,255,255,0.02)',
        marginHorizontal: SPACING.lg,
        borderRadius: RADIUS.lg,
        marginBottom: SPACING.lg,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.05)',
    },
    scrollContent: {
        padding: SPACING.lg,
        paddingBottom: 40,
    },
    sectionBlock: {
        marginBottom: SPACING.xl,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: FONT_WEIGHT.heavy,
        color: COLORS.textPrimary,
        marginBottom: 10,
        letterSpacing: 0.5,
    },
    sectionText: {
        fontSize: 14,
        color: COLORS.textSecondary,
        lineHeight: 24,
    },
    footer: {
        padding: SPACING.lg,
        backgroundColor: COLORS.surface,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.05)',
        paddingBottom: Platform.OS === 'ios' ? 34 : SPACING.lg,
    },
    scrollNotice: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(245, 158, 11, 0.1)',
        padding: 12,
        borderRadius: RADIUS.sm,
        marginBottom: SPACING.md,
    },
    scrollNoticeText: {
        color: COLORS.warning,
        fontSize: 11,
        fontWeight: FONT_WEIGHT.bold,
        marginLeft: 8,
        flex: 1,
    },
    checkboxContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: SPACING.lg,
        backgroundColor: 'rgba(34,197,94,0.05)',
        padding: 16,
        borderRadius: RADIUS.lg,
        borderWidth: 1,
        borderColor: 'rgba(34,197,94,0.2)',
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 4,
        borderWidth: 2,
        borderColor: COLORS.primary,
        marginRight: 12,
        marginTop: 2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkboxActive: {
        backgroundColor: COLORS.primary,
    },
    checkboxLabel: {
        flex: 1,
        fontSize: 12,
        color: COLORS.textPrimary,
        lineHeight: 18,
    },
    actionRow: {
        flexDirection: 'row',
        gap: 12,
    },
    declineBtn: {
        flex: 0.35,
        height: 54,
        borderRadius: RADIUS.full,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        backgroundColor: 'transparent',
    },
    declineBtnText: {
        color: COLORS.textMuted,
        fontSize: FONT_SIZE.md,
        fontWeight: FONT_WEIGHT.bold,
    },
    acceptBtn: {
        flex: 1,
        backgroundColor: COLORS.primary,
        height: 54,
        borderRadius: RADIUS.full,
        alignItems: 'center',
        justifyContent: 'center',
    },
    acceptBtnDisabled: {
        backgroundColor: 'rgba(34,197,94,0.2)',
    },
    acceptBtnText: {
        color: COLORS.white,
        fontSize: FONT_SIZE.md,
        fontWeight: FONT_WEIGHT.bold,
    },
    alertOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: SPACING.xl,
    },
    alertBox: {
        backgroundColor: COLORS.surface,
        borderRadius: RADIUS.lg,
        padding: SPACING.xl,
        width: '100%',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    alertIconBox: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: 'rgba(245, 158, 11, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: SPACING.md,
    },
    alertTitle: {
        fontSize: 18,
        fontWeight: FONT_WEIGHT.heavy,
        color: COLORS.textPrimary,
        marginBottom: SPACING.sm,
    },
    alertMessage: {
        fontSize: 14,
        color: COLORS.textSecondary,
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: SPACING.xl,
    },
    alertActionRow: {
        flexDirection: 'row',
        gap: 12,
        width: '100%',
    },
    alertCancelBtn: {
        flex: 1,
        height: 48,
        borderRadius: RADIUS.full,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,0.05)',
    },
    alertCancelBtnText: {
        color: COLORS.textPrimary,
        fontWeight: FONT_WEIGHT.bold,
    },
    alertConfirmBtn: {
        flex: 1,
        height: 48,
        borderRadius: RADIUS.full,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.danger,
    },
    alertConfirmBtnText: {
        color: COLORS.white,
        fontWeight: FONT_WEIGHT.bold,
    }
});
